### ISSUE TITLE
vm虚拟机 感染apk报错

### ISSUE THREAD

**Issue by stathamcheng** [virjarRatel/ratel-core#3]
BUILD SUCCESSFUL in 49s
134 actionable tasks: 51 executed, 83 up-to-date
engineVersionCode: 2.0.0-SNAPSHOT
test file:container-builder-repkg-2.0.0-SNAPSHOT.jar
use /home/virjar/Desktop/ratel/ratel-core/container-builder-repkg/build/libs/container-builder-repkg-2.0.0-SNAPSHOT.jar
java.lang.IllegalStateException: no infect apk passed
        at com.virjar.ratel.builder.ratelentry.BuilderContextParser.check(BuilderContextParser.java:66)
        at com.virjar.ratel.builder.ratelentry.BuilderContextParser.parse(BuilderContextParser.java:34)
        at com.virjar.ratel.builder.ratelentry.Main.ratelMain(Main.java:99)
        at com.virjar.ratel.builder.ratelentry.Main.main(Main.java:73)
assemble new apk for /Desktop/XX_9.25.0_apkcombo.com.apk
build with default certificate
error java.lang.IllegalStateException: no infect apk passed
java.lang.IllegalStateException: no infect apk passed
        at com.virjar.ratel.builder.ratelentry.BuilderContextParser.check(BuilderContextParser.java:66)
        at com.virjar.ratel.builder.ratelentry.BuilderContextParser.parse(BuilderContextParser.java:34)
        at com.virjar.ratel.builder.ratelentry.Main.ratelMain(Main.java:99)
        at com.virjar.ratel.builder.ratelentry.Main.main(Main.java:73)
task finish error
the final output apk file is :error java.lang.IllegalStateException: no infect apk passed
task finish error
virjar@virjar-aosp:~/Desktop/ratel/ratel-core$

**Comment by virjar** [comment]
apk地址传错了啊，
有“ /Desktop/XX_9.25.0_apkcombo.com.apk” 这个文件地址？？？你确定下

**Comment by stathamcheng** [comment]
解决了，我把apk放桌面了，执行命令时，“ /Desktop/XX_9.25.0_apkcombo.com.apk”这个路径前面加上~
